baseURL = "https://ivanpsg-br.github.io/Diario-de-um-Desenvolvedor-Determinado" # IMPORTANTE: Altere para seu futuro URL
languageCode = "pt-br"
title = "Diário de um Desenvolvedor Determinado"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
		hardWraps = true
		unsafe = true
[params]
  # Configurações do tema PaperMod
  defaultTheme = "dark" # Pode ser "light", "dark" ou "auto"
  ShowShareButtons = false
  ShowReadingTime = true
  ShowPostNavLinks = false
  disableSpecial1stPost = true
  ShowBreadCrumbs = false

[menus]
  [[menus.main]]
    identifier = "sobre"
    name = "Sobre"
	pageRef = "/"
    weight = 1000
  [[menus.main]]
    identifier = "dias"
    name = "Dias"
    pageRef = "/dias/"
    weight = 10
  [[menus.main]]
    identifier = "microtutoriais"
    name = "Microtutoriais"
    pageRef = "/microtutoriais/"
    weight = 20
